[versions]
kotlin = "2.2.21"
paper = "1.21.11-R0.1-SNAPSHOT"
testpaper = "1.21.10-R0.1-SNAPSHOT"

[libraries]
commons-provider = { module = "xyz.xenondevs.commons:commons-provider", version = "2.0.0-alpha.8" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version = "4.98.0"}
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.21" }
paperweight-userdev-plugin = { module = "io.papermc.paperweight:paperweight-userdev", version = "2.0.0-beta.19" }
test-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "testpaper" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }